# Generated by Django 5.2.2 on 2025-06-11 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Publications', '0004_alter_publications_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('public', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publications.publications')),
            ],
            options={
                'db_table': 'Paper',
                'ordering': ['-created'],
            },
        ),
    ]
