# Generated by Django 5.2.2 on 2025-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='author_en',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='author_ru',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='author_uz',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
