# Generated by Django 5.2.2 on 2025-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=450)),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'asked_questions',
            },
        ),
    ]
