# Generated by Django 5.2.2 on 2025-06-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='more_url',
        ),
    ]
