# Generated by Django 5.2.2 on 2025-06-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0002_remove_publications_more_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='media/images/'),
        ),
    ]
