# Generated by Django 5.2.2 on 2025-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0003_alter_publications_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='image',
            field=models.ImageField(default='media/publication/images/default.jpg', upload_to='media/publication/images/'),
        ),
    ]
