# Generated by Django 5.2.2 on 2025-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0004_alter_publications_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='tags_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='tags_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='tags_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
